### ISSUE TITLE
Problem Downloading Courses

### ISSUE THREAD

**Issue by robsee** [mrwnwttk/cloudacademy-dl#1]
Hi,

 While trying to download a course (or a dev path) I run into the following error. It only seems to happen at the third download:
Traceback (most recent call last):
  File "cloud.py", line 126, in <module>
    download_single_course(url)
  File "cloud.py", line 96, in download_single_course
    video_url, video_title = get_course_mp4_url_and_title(course_urls[u])
  File "cloud.py", line 57, in get_course_mp4_url_and_title
    for i in range(len(j["course"]["stepMap"][str(v)]["data"]["player"]["sources"])):
KeyError: 'sources'

I added a print to show the value of ["course"]["stepMap"][str(v)]["data"]["player"] and it the only json value in the output is 'transcript'

This is what the full output looks like:
Please enter a URL of the course you want to download: https://cloudacademy.com/course/designing-and-implementing-an-agile-work-management-approach-1017/
Downloading webpage...
Getting URLs of courses...
	https://cloudacademy.com/course/designing-and-implementing-an-agile-work-management-approach-1017/course-introduction/
	https://cloudacademy.com/course/designing-and-implementing-an-agile-work-management-approach-1017/project-metrics-and-kpis/
	https://cloudacademy.com/course/designing-and-implementing-an-agile-work-management-approach-1017/mentoring-team-members-on-agile-practices/
	https://cloudacademy.com/course/designing-and-implementing-an-agile-work-management-approach-1017/in-team-and-cross-team-collaboration/
	https://cloudacademy.com/course/designing-and-implementing-an-agile-work-management-approach-1017/tools-and-processes-for-agile-practices/
	https://cloudacademy.com/course/designing-and-implementing-an-agile-work-management-approach-1017/creating-organizational-structures-for-agile-practices/
	https://cloudacademy.com/course/designing-and-implementing-an-agile-work-management-approach-1017/course-conclusion/
Getting course title...
	Designing and Implementing an Agile Work Management Approach Course | Cloud Academy
Downloading videos...
Course Introduction - https://video.cloudacademy.com/5555_01-course-introduction_v2/video_6e752ad500f55672a78a7cf67f0c7cad-4_1920_1080.mp4?token=xxxx&expires=xxxxx
Project Metrics and KPIs - https://video.cloudacademy.com/5536_02-project-metrics-and-kpis/video_a43ce1a45ba77cca57fd01ad18cf083a-9_1920_1080.mp4?token=xxxx&expires=xxxxx
Mentoring Team Members on Agile Practices - https://video.cloudacademy.com/5537_03-mentoring-team-members-on-agile-practices/video_d244ff8cbfebecaf8e12d6dc41f23bfe-10_1920_1080.mp4?token=xxxxx&expires=xxxxx
Traceback (most recent call last):
  File "cloud.py", line 126, in <module>
    download_single_course(url)
  File "cloud.py", line 96, in download_single_course
    video_url, video_title = get_course_mp4_url_and_title(course_urls[u])
  File "cloud.py", line 57, in get_course_mp4_url_and_title
    for i in range(len(j["course"]["stepMap"][str(v)]["data"]["player"]["sources"])):
KeyError: 'sources'

**Comment by mrwnwttk** [comment]
I just tried to download this course and everything worksed just fine. You don't seem to be running the latest version (the line numbers don't match up), can you try updating and trying it again?

**Comment by robsee** [comment]
The differing line numbers were due to me adding some print statements. 
Just ran:git reset --hard
HEAD is now at 09a7779 Create .gitignore
Still the same problem:
cloudacademy-dl % python cloud.py
Loading cookie from file cookie.txt
Cookie read!
Please enter a URL of the course you want to download: https://cloudacademy.com/course/introduction-to-devops/
Downloading webpage...
Getting URLs of courses...
	https://cloudacademy.com/course/introduction-to-devops/intro-3/
	https://cloudacademy.com/course/introduction-to-devops/what-is-devops-1/
	https://cloudacademy.com/course/introduction-to-devops/why-culture-is-important-to-devops-1/
	https://cloudacademy.com/course/introduction-to-devops/why-automation-is-important-to-devops-1/
	https://cloudacademy.com/course/introduction-to-devops/why-metrics-are-important-to-devops-1/
	https://cloudacademy.com/course/introduction-to-devops/how-devops-can-improve-lead-time-1/
	https://cloudacademy.com/course/introduction-to-devops/how-devops-can-improve-stability-1/
	https://cloudacademy.com/course/introduction-to-devops/how-devops-can-reduce-operational-costs-1/
	https://cloudacademy.com/course/introduction-to-devops/what-companies-practice-devops-1/
	https://cloudacademy.com/course/introduction-to-devops/introduction-to-devops-summary-1/
Getting course title...
	Introduction to DevOps Course | Cloud Academy
Creating folder for videos...
Downloading videos...
Intro - https://video-legacy.cloudacademy.com/57309c37b903657e27d29b45/sources/video_1920_1080.webm?token=xxxx&expires=xxxx
What is DevOps? - https://video-legacy.cloudacademy.com/5730a22eb903657e26d3acca/sources/video_1920_1080.webm?token=xxxx&expires=xxxx
Traceback (most recent call last):
  File "cloud.py", line 123, in <module>
    download_single_course(url)
  File "cloud.py", line 94, in download_single_course
    video_url, video_title = get_course_mp4_url_and_title(course_urls[u])
  File "cloud.py", line 56, in get_course_mp4_url_and_title
    for i in range(len(j["course"]["stepMap"][str(v)]["data"]["player"]["sources"])):
KeyError: 'sources'

**Comment by mrwnwttk** [comment]
I think I might know what's wrong here. Did you sign up with either a demo account or a 7 day trial at least or did you just extract the cookie on the first visit? If you're not signed in in any way then you can only download previews of the last two courses. Of course in that case it doesn't work.

**Comment by robsee** [comment]
Ah ok. I did sign up for the trial account. I thought I had the cookie format correct (had to export it from Firefox), but its possible I screwed that part up. Its just the session guid looking cookie that I need, right (and should be in name=value in cookie.txt correct ?)

**Comment by mrwnwttk** [comment]
If you're exporting the cookie using some third-party extension then chances are you're not getting the right result. I'm using Chrome here but the process should be the exact same. Open up the website, log in and open the inspect tool. Refresh the page once. Right at the top of the list you should see the URL https://cloudacademy.com/
Click on that entry and on the right you should see a cookie parameter with a ton of text behind it. Copy that text and paste it into the document. No newlines, no extra spaces, nothing. Just that really long string.

**Comment by robsee** [comment]
Got it. Thanks for the help. You might want to clarify in the readme that you need the whole cookie block. I read it as you just need the clouda-session value. Also, for ease of use, you might want to strip the newline off of the end of the cookie if there is one. That was causing an error for me

**Comment by mrwnwttk** [comment]
So it's working now? In that case I'll add the suggested changes and then close this issue.

**Comment by robsee** [comment]
Yep, all set. Thanks.
