### ISSUE TITLE
How can we download all videos under category

### ISSUE THREAD

**Issue by npatel007** [mrwnwttk/cloudacademy-dl#2]
Hi, thank you for writing this code. It's working as expected with a single course link, is there any way we can provide batch url or whole category so it will download all the courses from that particular category? Thanks.

**Comment by mrwnwttk** [comment]
You can download entire learning paths using their respective urls, same goes for course libraries.

Examples:
https://cloudacademy.com/library/amazon-web-services/courses/
https://cloudacademy.com/library/amazon-web-services/learning-paths/

The only thing I haven't done yet is automatically putting courses of a single library into one folder.

**Comment by npatel007** [comment]
Ok thank you I dont know why i am getting this error with and without aria2c 

`
![image](https://user-images.githubusercontent.com/13300190/85505453-68565e00-b5ff-11ea-943b-4fc86772667f.png)
`
`C:\Users\xxx\cloudacademy-dl>py cloud.py --aria2c
Using aria2c for the downloads!
Loading cookie from file cookie.txt
Cookie read!
Please enter a URL of the course you want to download: https://cloudacademy.com/library/amazon-web-services/courses/
Going through the pages...
        https://cloudacademy.com/library/amazon-web-services/courses/?page=1
        https://cloudacademy.com/library/amazon-web-services/courses/?page=2
        https://cloudacademy.com/library/amazon-web-services/courses/?page=3
        https://cloudacademy.com/library/amazon-web-services/courses/?page=4
Number of courses: 122
Downloading webpage...
Getting URLs of courses...
        https://cloudacademy.com/course/amazon-aurora-high-availability/intro/
        https://cloudacademy.com/course/amazon-aurora-high-availability/amazon-aurora-ha-options/
        https://cloudacademy.com/course/amazon-aurora-high-availability/aurora-single-master-multiple-read-replicas/
        https://cloudacademy.com/course/amazon-aurora-high-availability/aurora-single-master-multiple-read-replicas-demo/
        https://cloudacademy.com/course/amazon-aurora-high-availability/aurora-multi-master/
        https://cloudacademy.com/course/amazon-aurora-high-availability/aurora-multi-master-setup-and-use-demo/
        https://cloudacademy.com/course/amazon-aurora-high-availability/aurora-serverless/
        https://cloudacademy.com/course/amazon-aurora-high-availability/aurora-serverless-database-cluster-demo/
        https://cloudacademy.com/course/amazon-aurora-high-availability/summary/
Getting course title...
        Amazon Aurora High Availability Course | Cloud Academy
Creating folder for videos...
Downloading videos...
Introduction - https://video.cloudacademy.com/4952_0_intro_v2/video_4719bf3dbd71b2c3dcb78b28c039ae91-2_1920_1080.webm?token=2-TC6jfvWoTVcqLbrctxAg&expires=1592998982

06/24 09:43:04 [NOTICE] Downloading 1 item(s)

06/24 09:43:05 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.
[#29b4e6 6.0MiB/6.0MiB(99%) CN:1 DL:2.3MiB]
06/24 09:43:07 [NOTICE] Download complete: C:/Users/xxx/cloudacademy-dl/Amazon Aurora High Availability Course - Cloud Academy/Introduction.webm

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
29b4e6|OK  |   2.0MiB/s|C:/Users/xxx/cloudacademy-dl/Amazon Aurora High Availability Course - Cloud Academy/Introduction.webm

Status Legend:
(OK):download completed.
Amazon Aurora HA Options - https://video.cloudacademy.com/4953_1_aurora_ha_options_v2/video_a100c84fce0a10ecd48c6f0f029bf295-11_1920_1080.webm?token=d1dViLVpvrqHIeFC6rHvLA&expires=1592998989

06/24 09:43:11 [NOTICE] Downloading 1 item(s)

06/24 09:43:12 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.
[#a73798 30MiB/32MiB(94%) CN:1 DL:2.2MiB]
06/24 09:43:32 [NOTICE] Download complete: C:/Users/xxx/cloudacademy-dl/Amazon Aurora High Availability Course - Cloud Academy/Amazon Aurora HA Options.webm

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
a73798|OK  |   1.5MiB/s|C:/Users/xxx/cloudacademy-dl/Amazon Aurora High Availability Course - Cloud Academy/Amazon Aurora HA Options.webm

Status Legend:
(OK):download completed.
Traceback (most recent call last):
  File "cloud.py", line 153, in <module>
    download_single_course(course)
  File "cloud.py", line 119, in download_single_course
    video_url, video_title = get_course_mp4_url_and_title(course_urls[u])
  File "cloud.py", line 57, in get_course_mp4_url_and_title
    for i in range(len(j["course"]["stepMap"][str(v)]["data"]["player"]["sources"])):
KeyError: 'sources'
`

**Comment by mrwnwttk** [comment]
It fails after exactly two videos inside a course. You didn't extract the cookie correctly. Please go through the README again.

**Comment by npatel007** [comment]
Yes you are right, I have messed up cookies fields  after copying from the chrome dev tools , i have found an extension  from chrome which does the job more easily, if you wish you can include this extention in readme file for future users.

https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg/related

**Comment by mrwnwttk** [comment]
As much as I would like to I feel like this would lead to far more people opening issues about the script not working when all they did was simply export the cookie.txt through some extension.
