### ISSUE TITLE
Can we skip the already downloaded videos while downloading the learning path.

### ISSUE THREAD

**Issue by talk2noob** [mrwnwttk/cloudacademy-dl#3]
my download got interrupted and few files downloaded.
when I try to download again, I see that downloading is starting from scratch again.
Is there a way in the script to download only the videos that are not downloaded.

**Comment by npatel007** [comment]
use aria2c i believe it will skip downloaded video

**Comment by mrwnwttk** [comment]
I already implemented that feature for libraries. I'll add it for learning paths too.

**Comment by mrwnwttk** [comment]
Done. Please check and see if it works for you.

**Comment by npatel007** [comment]
its not working i am having the same issue i re-run the script but instead of skipping it over writing   the files i am using this url 

https://cloudacademy.com/library/azure/courses/

**Comment by mrwnwttk** [comment]
It only does entire courses. It will re-download every video if a course is not finished yet, that's to be expected.

**Comment by npatel007** [comment]
thanks for the quick reply but is there any way i have many courses in the individual folders that are completed but its getting overwritten i am currently playing with passing aria2c flag but that's not working either

```` python3 cloud.py --aria2c --auto-file-renaming=false ```

is there anyway we can skip the already downloaded files with in the course

**Comment by mrwnwttk** [comment]
Oh right, you downloaded the courses before the feature was added, therefore none of the links are in the list.

You can add the -c flag to aria2c for this.
