### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bormenta1** [mrwnwttk/cloudacademy-dl#4]
`Traceback (most recent call last):
  File "cloud.py", line 177, in <module>
    download_single_course(url)
  File "cloud.py", line 125, in download_single_course
    video_url, video_title = get_course_mp4_url_and_title(course_urls[u])
  File "cloud.py", line 63, in get_course_mp4_url_and_title
    for i in range(len(j["course"]["stepMap"][str(v)]["data"]["player"]["sources"])):
`

**Comment by mrwnwttk** [comment]
What course did this happen on?
What are you running the script on?
Are you using a demo, trial or paid account?
Are you able to watch the videos of the selected course in the browser?
Did you follow all the cookie steps in the readme? 

Come on, you've gotta give me some more information than just the last three lines of an error message.

**Comment by bormenta1** [comment]
python3 cloud.py --aria2
Loading cookie from file cookie.txt
Cookie read!
Please enter a URL of the course you want to download: https://cloudacademy.com/learning-paths/working-with-aws-databases-274/

Number of courses: 4
Downloading course [1 / 4]
Downloading webpage...
Getting URLs of courses...
	https://cloudacademy.com/course/aws-database-fundamentals-aws-180/introduction-17/
	https://cloudacademy.com/course/aws-database-fundamentals-aws-180/what-is-a-cloud-database/
	https://cloudacademy.com/course/aws-database-fundamentals-aws-180/databases-overview/
	https://cloudacademy.com/course/aws-database-fundamentals-aws-180/amazon-non-relation-databases-depth/
	https://cloudacademy.com/course/aws-database-fundamentals-aws-180/non-relational-databases/
	https://cloudacademy.com/course/aws-database-fundamentals-aws-180/aws-rds-databases/
	https://cloudacademy.com/course/aws-database-fundamentals-aws-180/considerations-and-troubleshooting/
	https://cloudacademy.com/course/aws-database-fundamentals-aws-180/db-fundamentals-summary/
Getting course title...
	Database Fundamentals for AWS Course | Cloud Academy
Creating folder for videos...
Downloading videos...
Introduction - https://video.cloudacademy.com/2424_1database-fundamentals-introduction/video_327a5d6ee0cc3a999b573ae0262f9d04-3_1920_1080.webm?token=uru7RglMdSRfbDqtktk0Tg&expires=1593104642
What is a Cloud Database? - https://video.cloudacademy.com/2425_2database-fundamentals-the-basics/video_cd36295d7f4d06d8389fc3b50dc73fdc-32_1920_1080.mp4?token=jx56OsB7q7ZKwBVdj1ezxw&expires=1593104647
Traceback (most recent call last):
  File "cloud.py", line 179, in <module>
    download_learning_path(url)
  File "cloud.py", line 152, in download_learning_path
    download_single_course(learning_path_courses[course])
  File "cloud.py", line 125, in download_single_course
    video_url, video_title = get_course_mp4_url_and_title(course_urls[u])
  File "cloud.py", line 63, in get_course_mp4_url_and_title
    for i in range(len(j["course"]["stepMap"][str(v)]["data"]["player"]["sources"])):
KeyError: 'sources'

**Comment by bormenta1** [comment]
Any course, same error

**Comment by mrwnwttk** [comment]
You didn't actually answer the majority of my questions, but given that it fails on the second video of a course you most likely didn't use a proper cookie. Please go through the README again.
