### ISSUE TITLE
can't use cookies

### ISSUE THREAD

**Issue by dexter101010** [mrwnwttk/cloudacademy-dl#5]
Hi, 

I did try your script but i get this error:

E:\Cloud>python cloud.py
Loading cookie from file cookie.txt
Could not read cookie! Exiting...

I was trying to get cookies like you said : login and after that F12, ctrl+r , find this https://cloudacademy.com/, add the content into a file named cookies. But like i said, i get that error . 

Also i want to mention that first thing that i am finding is this : 

https://cloudacademy.com/dashboard/activity/

I do right click on this and i have tried all options: copy as fetch, as powershell, as bash. But no luck.

**Comment by mrwnwttk** [comment]
I made a small video showing how to do the whole cookie thing. Please take a look and tell me if it works when replicating the steps.

https://youtu.be/agFFXll55eE

**Comment by dexter101010** [comment]
> I made a small video showing how to do the whole cookie thing. Please take a look and tell me if it works when replicating the steps.
> 
> https://youtu.be/agFFXll55eE

Hi man, 

Thank you for your fast reply. I did the same like you did in the video, but i get the same result : 

E:\Cloud>python cloud.py
Loading cookie from file cookie.txt
Could not read cookie! Exiting...


This is how it looks my cookie file :  


clouda-session=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx; csrftoken=U7kPBtu83eeql15v7qNgmmANiqFPwdEgS7UUbcMzgli6LfEEUkZIKXZF7xynDu4x; sessionid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; ca_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcnJpZXV4ZXJpY2tAZ21haWwuY29tIiwib3JpZ19pYXQiOjE1OTMzNDg1NDQsImZlYXR1cmVzIjpbXSwiY29ybl9jb21wYW55X2FjY291bnRfaWQiOm51bGwsImNvbXBhbnlfYWNjb3VudF9pZCI6bnVsbCwibWVtYmVyc2hpcF90aWVyIjoiaW5kaXZpZHVhbCIsInVzZXJfaWQiOjMyOTUwNSwiY3VzdG9tZXJfbGlmZWN5Y2xlIjoic3Vic2NyaXB0aW9uLWFjdGl2ZSIsInRlbmFudF9pZCI6ImNsb3VkYWNhZGVteSIsImNvbXBhbnlfYWNjb3VudF9kb2VzX2NyZWF0ZV9wdWJsaWNfY29udGVudCI6bnVsbCwiYWN0b3JfaWQiOiI1ZWM0ZDdlYWU5NDVlZjBiZjRhY2EyZmYiLCJleHAiOjE1OTMzNDk3NDQsImVtYWlsIjoibGFycmlldXhlcmlja0BnbWFpbC5jb20ifQ.DNoM7jUN8Fnf7XHKAy67NQ1vhD0fHp_xxxxxxxxxxxx

**Comment by mrwnwttk** [comment]
Oh in that case python couldn't even open the cookie.txt file! Can you run the command `dir` inside that directory and send me the result?

**Comment by dexter101010** [comment]
> Oh in that case python couldn't even open the cookie.txt file! Can you run the command `dir` inside that directory and send me the result?

Hi man, 

I have found where the issue is. Cookie was written cookies.  Thanks for your help :D

**Comment by mrwnwttk** [comment]
Okay, glad I could help! :)

I'll go ahead and close this issue if there are no further problems.

**Comment by dexter101010** [comment]
> Okay, glad I could help! :)
> 
> I'll go ahead and close this issue if there are no further problems.

Ok. Thanks again :)
