### ISSUE TITLE
Script fails as one of the course in Learning path is not free

### ISSUE THREAD

**Issue by CG123CG** [mrwnwttk/cloudacademy-dl#6]
Hello,
Thanks for the script. I came across an issue and found that it fails as 1 of the course in Learning path is not free.
Course that causes issue
https://cloudacademy.com/course/visualization-tools/

Course Library impacted as of now
https://cloudacademy.com/library/machine-learning/courses/
https://cloudacademy.com/library/big-data/courses/
https://cloudacademy.com/library/partner-ecosystem/courses/
https://cloudacademy.com/library/programming/courses/

As the above course is the first in the list to fetch, it fails just after creating folder.

As I'm not into Python, I could only think of putting a IF NOT statement in line 115 to check if title matches above course, and if so skip the rest of the function. Although I haven't tried it yet.

Error msg is similar to this and comes only for above 3 URLs. 

> File "cloud.py", line 125, in download_single_course
> video_url, video_title = get_course_mp4_url_and_title(course_urls[u])
> File "cloud.py", line 63, in get_course_mp4_url_and_title
> for i in range(len(j["course"]["stepMap"][str(v)]["data"]["player"]["sources"])):
> KeyError: 'sources'

Please see if you could find time to help.

Thanks, ChenG

**Comment by mrwnwttk** [comment]
Try to clone the dev branch and use that version. It ignores failed courses. Let me know if that works! I'll eventually merge that into the master branch.

**Comment by CG123CG** [comment]
> 
> 
> Try to clone the dev branch and use that version. It ignores failed courses. Let me know if that works! I'll eventually merge that into the master branch.

thanks for replying. Unfortunately as the free period had ended, I cannot check the fix you have implemented.

For my issue, I tried following options and they worked
1. check for Title - failed as title isn't defined
2. At line 170, started from course+1 to avoid the 1st course, download_single_course(all_the_courses[course]**+1**) - Worked fine
3. Added course URL to downloaded_courses.txt  - Worked fine.

I'll check the Dev branch code once the free period opens in coming months and update back.

Thanks ChenG

**Comment by JLOPS** [comment]
Unfortunately latest script doesn't work for paid videos:

Traceback (most recent call last):
  File "../cloud.py", line 179, in <module>
    download_learning_path(url)
  File "../cloud.py", line 152, in download_learning_path
    download_single_course(learning_path_courses[course])
  File "../cloud.py", line 125, in download_single_course
    video_url, video_title = get_course_mp4_url_and_title(course_urls[u])
  File "../cloud.py", line 63, in get_course_mp4_url_and_title
    for i in range(len(j["course"]["stepMap"][str(v)]["data"]["player"]["sources"])):
UnboundLocalError: local variable 'v' referenced before assignment

There's a parameter to skip that URIs?

Thanks so much, awesome work!
