### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by Siddharth-Selvarajan** [mrwnwttk/cloudacademy-dl#7]
After Login, I got bellow error (Both Windows & Linux)

UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)

Please Guide me.

**Comment by mrwnwttk** [comment]
What course is this happening on? Python should give have given you a line number for the error, which one is it?

**Comment by Siddharth-Selvarajan** [comment]
All Courses,  

Traceback (most recent call last):
  File "cloud.py", line 177, in <module>
    download_single_course(url)
  File "cloud.py", line 99, in download_single_course
    r = requests.get(url, headers=headers)

![image](https://user-images.githubusercontent.com/69203685/90377309-75d71400-e095-11ea-9ed6-9ce46afd6329.png)

**Comment by Siddharth-Selvarajan** [comment]
thanks. Cookies error. problem solved.
